### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by Saloed** [TheBigBagrovski/JavaAsSecond2021#1]
1. Кажется в [этом](https://github.com/TheBigBagrovski/JavaAsSecond2021/blob/c78d29cc32f07802deeebc80919ce975bcc23a9b/src/exercise1/BinaryTree.java#L78) случае лучше кидать исключение.
2. Сейчас [вот здесь](https://github.com/TheBigBagrovski/JavaAsSecond2021/blob/c78d29cc32f07802deeebc80919ce975bcc23a9b/src/exercise1/BinaryTree.java#L166) дети сравниваются по ссылке, что не очень правильно. 
3. NPE это всегда не очень хорошо. Это исключение обычно показывает, что что-то пошло очень не так и всё сломалось. Если такая ситуация ожидаема и предусмотрена логикой работы вашего дерева, то лучше это нормально обработать и кинуть, например, `IllegalStateException`.  [link](https://github.com/TheBigBagrovski/JavaAsSecond2021/blob/c78d29cc32f07802deeebc80919ce975bcc23a9b/src/exercise1/Tests.java#L52)
4. У вас получился какой-то перегруженный тестовый сценарий [link](https://github.com/TheBigBagrovski/JavaAsSecond2021/blob/c78d29cc32f07802deeebc80919ce975bcc23a9b/src/exercise1/Tests.java#L64). Сначала вы что-то проверяете, а потом ещё проверяете, что полетит исключение. Старайтесь делать маленькие тестовые сценарии и давать им нормальные имена. Так будет понятно, какую именно ситуацию проверяет данный тест, и если он упадёт, то тоже будет проще понять, что именно сломалось.
5.  Создание какого-то начального не пустого дерева возможно лучше вынести в отдельную функцию.

**Comment by Saloed** [comment]
1. В игноре хотелось бы увидеть ещё: `.gradle` -- локальные кэши системы gradle, `build` -- результаты сборки системой gradle, `exercise1.iml` -- файл с конфигурацией модуля из idea. 
2. Проверьте, что gradle настроен хорошо и через него можно запускать тесты. Для этого запустите задачу test у gradle. Как это сделать в idea можно почитать [здесь](https://www.jetbrains.com/help/idea/work-with-gradle-tasks.html#gradle_tasks).
3. `Main` можно удалить. Он не очень нужен, поскольку есть тесты. 
4. Тесты выглядят хорошо. 
5. По поводу `equals`.  Небольшой пример, с разницей сравнения по ссылке и через `equals` (если он правильно переопределён). 
```java
class A{
    int x;
    
    A (int x) {
        this.x = x;
    }
    
    @Override
    public boolean equals(Object other){
        if (this == other) return true;
        if (!(other instanceof A)) return false;
        return this.x == ((A) other).x;
    }
    
}

public static void main(String []args){
  A a = new A(3);
  A b = new A(3);
  System.out.println("By reference: " + (a == b)); // false
  System.out.println("By equals: " + (a.equals(b))); // true
}
```

Теперь возвращаясь к вашим `Node`.  Если вы сравниваете детей по ссылке, то может оказаться, что для одинаковых с точки зрения `equals` детей результат `false`, поскольку у них разные ссылки. Поэтому, логичнее их также сравнить через `equals`.

**Comment by TheBigBagrovski** [comment]
Удалил `Main`. Изменил gitignore. 
Таск `test `выдает` test events were not received`, долго гуглил, но исправить не смог.
Изменил `equals`, теперь сравнивается только значение двух узлов, по условию числа не повторяются, поэтому детей сравнивать вроде вообще нет смысла.

**Comment by Saloed** [comment]
1. Не очень понятно, зачем вашему классу зависимость от библиотеки для тестов. [link](https://github.com/TheBigBagrovski/JavaAsSecond2021/blob/91532b05b327d50f2cf84fbcf5a43df3b654d407/build.gradle#L24)
2. Всё таки тесты нужно хранить отдельно от кода. Причём разделение на директории с кодом и тестами должно быть сделано на верхнем уровне. Например: `src/<package name>/X.java` и `test/<package name>/XTest.java`
3. Ещё немного про [source root](https://github.com/TheBigBagrovski/JavaAsSecond2021/blob/91532b05b327d50f2cf84fbcf5a43df3b654d407/build.gradle#L14). Source root это директория, внутри которой gradle ищет пакеты с кодом. Например, файл `X.java` с пакетом `a.b`, должен находится в `<source root>/a/b/X.java`. 
У вас получилось немного странненько, потому что вы в `source root` вписали `src/excercise1` и пакет у вас называется `excercise1`. В итоге получилось, что файлы с кодом нужно класть в `src/excercise1/excercise1`. Если бы вы сделали source root `src`, то было бы по приятнее, т.к. код можно было бы класть в `src/excercise1`. 
4. Вы точно знаете, что делает [вот эта строчка](https://github.com/TheBigBagrovski/JavaAsSecond2021/blob/91532b05b327d50f2cf84fbcf5a43df3b654d407/build.gradle#L30)?
